
let scene, camera, renderer;
let cannonBalls = [];
//stores balls

let ballMeshes = [];
//stores mesh of balls which defines geometry and material

let cannonBody, cannonMesh;
// stores the cannon body and its mesh

let groundBody, groundMesh;
// strores ground and its mesh

let gravity = 9.8;
let cannonAngle = 45;
let ballSpeed = 20;
let ballCount = 5;
let ballSize = 0.5;
//default physics parameters
let world;
//creating a variable for the world 


function initialize () {

    scene = new THREE.Scene();
    scene.background = new THREE.Color(0x0a1929);
    //sets background color
    scene.fog = new THREE.Fog(0x0a1929, 20, 50);
    // adds fog so that balls that are farther away can fade into the background
    camera = new THREE.PerspectiveCamera(
    60,
    window.innerWidth / window.innerHeight,
    0.1,
    1000
    )
    //creates a perspective camera with field of view, aspect ratio, and near and far parameters
    camera.position.set(0, 5, 15);
    //positions camera

    camera.lookAt(0, 0, 0);
    //where the camera is looking at, the area that is being seen
    renderer = new THREE.WebGLRenderer();
    renderer.setSize(
      document.getElementById('scene-container').offsetWidth,
      document.getElementById('scene-container').offsetHeight
    )
    renderer.shadowMap.enabled = true;
    //allows shadows
    document.getElementById('scene-container').appendChild(renderer.domElement);
    //adds the scene to the html so that it is visible

    world = new CANNON.World();
    world.gravity.set(0, -gravity, 0);
    
    const ambientLight = new THREE.AmbientLight(0xffffff, 1.0);
    scene.add(ambientLight);
    const directionalLight = new THREE.DirectionalLight(0xffffff, 1.8);
    directionalLight.position.set(5, 10, 7);
    directionalLight.castShadow = true;
    //allows the light to create shadow
    //creates a light that appears to be coming from a strong light source
    scene.add(directionalLight);


    const groundGeometry = new THREE.PlaneGeometry(20, 20);
    const groundMaterial = new THREE.MeshStandardMaterial({
    color: 0x2a5b3c
  })
  
    groundMesh = new THREE.Mesh(groundGeometry, groundMaterial);
    groundMesh.rotation.x = -Math.PI / 2;
    //rotates the ground 90 degrees so that it faces the camera

  

    groundMesh.receiveShadow = true;
    //allows for the balls to create shadows on the ground
    scene.add(groundMesh);

  

    const groundShape = new CANNON.Plane();
    groundBody = new CANNON.Body({ mass: 0 });
    groundBody.addShape(groundShape);
    groundBody.quaternion.setFromAxisAngle(new CANNON.Vec3(1, 0, 0), -Math.PI / 2);
    //rotates y-axis 90 degrees so that it is facing upwards and gravity can work
    world.addBody(groundBody);


    createCannon();

    setupEventListeners();

    animate();
}

function createCannon () {

    if (cannonMesh) {
      scene.remove(cannonMesh)
    }

    const cannonShape = new CANNON.Box(new CANNON.Vec3(0.5, 0.2, 0.2));
    //line 112 was generated by ai 
    cannonBody = new CANNON.Body({ mass: 0 });
    cannonBody.addShape(cannonShape);
    cannonBody.position.set(0, 0.2, 0);
    world.addBody(cannonBody);
    //positions the cannon


    const cannonGeometry = new THREE.BoxGeometry(1, 0.4, 0.4);
    const cannonMaterial = new THREE.MeshStandardMaterial({
      color: 0x333333,
      metalness: 0.7,
      roughness: 0.3
  })

    cannonMesh = new THREE.Mesh(cannonGeometry, cannonMaterial);
    cannonMesh.castShadow = true;
    scene.add(cannonMesh);
}

function launchBalls () {

  clearBalls()

  current_ball_speed = ballSpeed;

  for (let i = 0; i < ballCount; i++) {
    ballSpeed = current_ball_speed + i
    createBall()
  }
    ballSpeed = current_ball_speed;
  //adds i for each ball's velocity because otherwise they all overlap
}

function createBall () {

    const ballShape = new CANNON.Sphere(ballSize);
    const ballBody = new CANNON.Body({ mass: 1 });
    ballBody.addShape(ballShape);


    ballBody.position.set(0, 0.5, 0);

    const radians = (cannonAngle * Math.PI) / 180;
    const velocityX = ballSpeed * Math.cos(radians);
    const velocityZ = ballSpeed * Math.sin(radians);
    //converts launch angle to radians
    //splits velocity into components

    ballBody.velocity.set(velocityX, 0, velocityZ);
    //sets the velocity 
    world.addBody(ballBody);
    cannonBalls.push(ballBody);


    const ballGeometry = new THREE.SphereGeometry(ballSize, 32, 32);
    const ballMaterial = new THREE.MeshStandardMaterial({
      color: new THREE.Color(Math.random() * 0xffffff),
      //multiplies the largest value of the color range with a factor
      //lines 167-169 are generated by ai
      metalness: 0.3,
      roughness: 0.4
  })

    const ballMesh = new THREE.Mesh(ballGeometry, ballMaterial);
    ballMesh.castShadow = true;
    scene.add(ballMesh);
    ballMeshes.push(ballMesh);
    //allows the ball to create a shadow
    //push adds the ball mesh to the array
}

function clearBalls () {

    for (const ball of cannonBalls) {
      world.removeBody(ball);
    }

    for (const mesh of ballMeshes) {
      scene.remove(mesh);
    }

}
//removes the mesh and ball

function setupEventListeners () {
 
  const gravitySlider = document.getElementById('gravity');
  const gravityValue = document.getElementById('gravity-value');

  gravitySlider.addEventListener('input', function () {
    gravity = parseFloat(this.value);
    gravityValue.textContent = gravity;
    world.gravity.set(0, -gravity, 0);
  })
  //gets the value of gravity from the slider

  const cannonAngleSlider = document.getElementById('cannon-angle');
  const cannonAngleValue = document.getElementById('cannon-angle-value');

  cannonAngleSlider.addEventListener('input', function () {
    cannonAngle = parseInt(this.value);
    cannonAngleValue.textContent = cannonAngle;
    updateCannonOrientation();
  })
  //gets the value of the launch angle from slider

  const ballSpeedSlider = document.getElementById('ball-speed');
  const ballSpeedValue = document.getElementById('ball-speed-value');

  ballSpeedSlider.addEventListener('input', function () {
    ballSpeed = parseInt(this.value);
    ballSpeedValue.textContent = ballSpeed;
  })
  //gets the value of velocity from slider


    const ballCountSlider = document.getElementById('ball-count');
    const ballCountValue = document.getElementById('ball-count-value');
  
  ballCountSlider.addEventListener('input',function () {
    ballCount = parseInt(this.value);
    ballCountValue.textContent = ballCount;
  })


    const ballSizeSlider = document.getElementById('ball-size');
    const ballSizeValue = document.getElementById('ball-size-value');

  ballSizeSlider.addEventListener('input', function () {
    ballSize = parseFloat(this.value);
    ballSizeValue.textContent = ballSize;
  })


    document.getElementById('launch-btn').addEventListener('click', launchBalls)

  window.addEventListener('resize', function () {
    camera.aspect =
      document.getElementById('scene-container').offsetWidth /
      document.getElementById('scene-container').offsetHeight;
    camera.updateProjectionMatrix()
    renderer.setSize(
      document.getElementById('scene-container').offsetWidth,
      document.getElementById('scene-container').offsetHeight
    );
  })
}
//lines 249-259 were generated by ai 
//makes the scene maintain the same proportions when the window is resized
function updateCannonOrientation () {

  if (cannonBody) {
    const radians = (cannonAngle * Math.PI) / 180;
    cannonBody.quaternion.setFromAxisAngle(new CANNON.Vec3(0, 1, 0), radians);
    //sets angle with respect to the y-axis
  }
}

function animate () {
    requestAnimationFrame(animate);


    world.step(1 / 60);
  //animation update time

  for (let i = 0; i < cannonBalls.length; i++) {
    ball = cannonBalls[i];
    if (i < ballMeshes.length) //checks if the ball mesh and ball have been created
    {
      ballMeshes[i].position.copy(ball.position);
      ballMeshes[i].quaternion.copy(ball.quaternion);
    }
  }
  // lines 277-285 were generated by ai
  //makes the ball mesh have the same position and rotation as the ball


  renderer.render(scene, camera);
}


window.onload = initialize;
// this file has used help from generative ai
